theme: jekyll-theme-tactile
title: Welcome to the Vadim's homepage!
description: Feel free to bookmark this to keep an eye on my project updates.
readme_index:
  enabled:          true
  remove_originals: false
